apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  namespace: petclinic
  labels:
    app: tracing-server
    component: infrastructure
spec:
  type: ClusterIP
  selector:
    app: tracing-server
  ports:
    - port: 9411
      targetPort: http
      protocol: TCP
      name: http
